config/routes.rb
Rails.application.routes.draw do

  
  resources :ping

  root 'welcome#index'

end

app/models/ping.rb
class Ping < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ping_controller.rb
class PingController < ApplicationController
  def new
  end

  def create
    obj = S3_BUCKET.objects['photo-ping']
    @file = Rails.root + "app/assets/ping.txt"
    
    obj.write(
      file: @file,
      acl: :public_read
      )
    
    @ping = Ping.new(
      url: obj.public_url,
      name: obj.key
      )
      
    if @ping.save
      redirect_to new_ping_path
      flash[:success] = "You've sent calibration request through the interwebs.... standby"
    else
      flash.now[:danger] = "Something went wrong, let's see.."
      render :new
    end
      
  end
  
  def index
    
  end
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ping_helper.rb
module PingHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/ping/create.html.haml
%h1 Ping#create
%p Find me in app/views/ping/create.html.haml

app/views/ping/new.html.haml
.container
  %h1 Click for Snapshot

  = form_tag ping_index_path, enctype: 'multipart/form-data' do
  
    = submit_tag 'Snapshot', class: "btn btn-lg btn-warning"
    
  - S3_BUCKET.objects.each do |object|
    
    = object.key
    %br
    = image_tag("https://matt-photo-app.s3.amazonaws.com/#{object.key}")
    
    
    // = object.read
    // https://<bucket-name>.s3.amazonaws.com/<key>
    // https://matt-photo-app.s3.amazonaws.com/image-2016-04-08 18:02:43.319729.jpg
  // = image_tag("https://matt-photo-app.s3.amazonaws.com/image-2016-04-08 18:02:43.319729.jpg")

app/views/welcome/index.html.haml
.container
    =image_tag('elemental-machines-logo.png', class: "background")
    %h1 Welcome to Elemental Camera Dashboard
    
    
    %h4 Click below for Camera Adjustment:
    =link_to "Snapshot", new_ping_path, class: "btn btn-primary"